FROM fj0rd/rs as build

WORKDIR /app
COPY drone /app
RUN set -eux \
  ; cargo build --release

FROM fj0rd/k8su:latest

COPY drone/kube_config.yml /kube_config.yml
ENV KUBECONFIG=/kube_config.yml

COPY --from=build /app/target/release/drone /usr/bin
ENTRYPOINT ["/usr/bin/drone"]
