---
apiVersion: v1
kind: Config
users:
  - name: ci
    user:
      token: "<token>"
clusters:
  - cluster:
      certificate-authority-data: "<cert>"
      server: 127.0.0.1
    name: target
contexts:
  - context:
      cluster: target
      namespace: "<ns>"
      user: ci
    name: deployment
current-context: deployment